development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000


# development:
#   adapter: oracle_enhanced
#   database: 10.30.0.22:1521/dese01
#   username: ticketer
#   password: ticketer
#   pool: 5
#   timeout: 5000

test:
  adapter: oracle_enhanced
  database: 10.30.0.81:1521/simu01
  username: ticketer
  password: ticketer
  pool: 5
  timeout: 5000

production:
  adapter: oracle_enhanced
  database: 10.30.5.8:1522/prod01
  username: ticketer
  password: ticketer
  pool: 5
  timeout: 5000
